{ pkgs, config, lib, inputs, ...}:

{  
  wayland.windowManager.hyprland = {
    enable = true;
    package = null;
    portalPackage = null;
    plugins = [ inputs.hypr-dynamic-cursors.packages.${pkgs.system}.hypr-dynamic-cursors ];

    settings = {
      autogenerated = 0;
      monitor = [
        "eDP-1,1920x1080@60.01, 0x0, 1"
        ",preferred,auto,1,mirror,eDP-1"
      ];
      "$mainMod" = "SUPER";
      "$terminal" = "kitty";
      "$fileManager" = "dolphin";
      "$menu" = "wofi --show drun";
  
      general = {
        gaps_in = 5;
        gaps_out = 20;
        "col.active_border" = lib.mkDefault "rgba(33ccffee) rgba(00ff99ee) 45deg";
        "col.inactive_border" = lib.mkDefault "rgba(595959aa)";
        border_size = 0;

        resize_on_border = false;
        allow_tearing = false;
        layout = "dwindle";
      };
  
      decoration = {
        rounding = 10;
        rounding_power = 2;
        active_opacity = 1.0;
        inactive_opacity = 1.0;
  
        shadow = {
	  enabled = "true";
	  range = 4;
	  render_power = 3;
	  color = lib.mkDefault "rgba(1a1a1aee)";
        };
  
        blur = {
	  enabled = "true";
	  size = 3;
	  passes = 1;
	  vibrancy = 0.1696;
        };
      };
  
      input = {
        kb_layout = "latam";
        #kb_variant =
        #kb_model =
        #kb_options =
        #kb_rules =
    
        follow_mouse = 1;
    
        sensitivity = 0; # -1.0 - 1.0, 0 means no modification.
    
        touchpad = {
            natural_scroll = "true";
        };
      };
  
      device = {
        name = "epic-mouse-v1";
        sensitivity = "-0.5";
      };
  
      gestures = {
        workspace_swipe = "true";
      };
  
      misc = {
        #force_default_wallpaper = 1;
        #disable_hyprland_logo = "true";
      };
  
      bind = [
        "$mainMod, RETURN, exec, $terminal"
        "$mainMod SHIFT, Q, killactive"
        "$mainMod SHIFT, E, exit"
        "$mainMod SHIFT, SPACE, togglefloating"
        "$mainMod, D, exec, $menu"
	"$mainMod, F, fullscreen"
	", PRINT, exec, hyprshot -m region --clipboard-only"
	"$mainMod, PRINT, exec, hyprshot -m window"

	"$mainMod, h, movefocus, l"
        "$mainMod, l, movefocus, r"
        "$mainMod, k, movefocus, u"
        "$mainMod, j, movefocus, d"
  
        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, 6, workspace, 6"
        "$mainMod, 7, workspace, 7"
        "$mainMod, 8, workspace, 8"
        "$mainMod, 9, workspace, 9"
  
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod SHIFT, 6, movetoworkspace, 6"
        "$mainMod SHIFT, 7, movetoworkspace, 7"
        "$mainMod SHIFT, 8, movetoworkspace, 8"
        "$mainMod SHIFT, 9, movetoworkspace, 9"
        "$mainMod SHIFT, 0, movetoworkspace, 10"
  
        "$mainMod, S, togglespecialworkspace, magic"
        "$mainMod SHIFT, S, movetoworkspace, special:magic"
      ];
  
      "exec-once" = [ 
        "waybar"
  #      "hyprpaper"
      ];
  
      "plugins:dynamic-cursors" = {
         enabled = "true";
         mode = "stretch";
         threshold = 2;
  
         shake = {
               # enables shake to find
           enabled = "true";
  
          # use nearest-neighbour (pixelated) scaling when shaking
          # may look weird when effects are enabled
           nearest = "true";
  
          # controls how soon a shake is detected
          # lower values mean sooner
           threshold = 6.0;
  
          # magnification level immediately after shake start
           base = 4.0;
          # magnification increase per second when continuing to shake
           speed = 4.0;
          # how much the speed is influenced by the current shake intensitiy
           influence = 0.0;
  
          # maximal magnification the cursor can reach
          # values below 1 disable the limit (e.g. 0)
           limit = 0.0;
  
          # time in millseconds the cursor will stay magnified after a shake has ended
           timeout = 2000;
  
          # show cursor behaviour `tilt`, `rotate`, etc. while shaking
           effects = "false";
  
          # enable ipc events for shake
          # see the `ipc` section below
           ipc = "false";
         };
      };
    };
  };
}
