{ pkgs, config, lib, inputs, ...}:
let 
  host = config.home.sessionVariables.HOSTNAME or "default";
  monitorConfig = {
    "maelstrom" = [
      "eDP-1, 1920x1080@60.01, 0x0, 1" ",preferred, auto, 1, mirror, eDP-1"
    ];
    "vortex" = [
      "HDMI-A-1, 1920x1080@75.01, 0x0, 1" ",preferred, auto, 1, mirror, HDMI-A-1"
    ];
    "default" = [
      "eDP-1, auto, 0x0, 1" ",preferred, auto, 1, mirror, eDP-1"
    ];
  };
  selectedMonitor = monitorConfig.${host} or monitorConfig."default";
  pyprlandToml = ./pyprland/pyprland.toml;
in {  

  xdg.configFile."hypr/pyprland.toml".source = pyprlandToml;
  wayland.windowManager.hyprland = {
    enable = true;
    package = null;
    portalPackage = null;
    plugins = [ 
      inputs.hypr-dynamic-cursors.packages.${pkgs.system}.hypr-dynamic-cursors
    ];

    settings = {
      autogenerated = 0;
      monitor = selectedMonitor;

      "$mainMod" = "SUPER";
      "$terminal" = "kitty";
      "$fileManager" = "dolphin";
      "$menu" = "bemenu-run -b";

      general = {
        gaps_in = 5;
        gaps_out = 20;
        "col.active_border" = lib.mkDefault "rgba(33ccffee) rgba(00ff99ee) 45deg";
        "col.inactive_border" = lib.mkDefault "rgba(595959aa)";
        border_size = 0;

        resize_on_border = true;
        allow_tearing = false;
        layout = "dwindle";
      };

      decoration = {
        rounding = 10;
        rounding_power = 2;
        active_opacity = 1.0;
        inactive_opacity = 1.0;

        shadow = {
          enabled = "false";
          range = 4;
          render_power = 3;
          color = lib.mkDefault "rgba(1a1a1aee)";
        };

        blur = {
          enabled = "true";
          size = 8;
          passes = 2;
          vibrancy = 0.1696;
          ignore_opacity = true;
          xray = true;
          special = false;
        };
      };

      animations = {
        enabled = "no";
        bezier = [
          "easeOutQuint,0.23,1,0.32,1"
          "easeInOutCubic,0.65,0.05,0.36,1"
          "linear,0,0,1,1"
          "almostLinear,0.5,0.5,0.75,1.0"
          "quick,0.15,0,0.1,1"
        ];
      };

      input = {
        kb_layout = "latam";
        #kb_variant =
        #kb_model =
        #kb_options =
        #kb_rules =

        follow_mouse = 1;

        sensitivity = 0; # -1.0 - 1.0, 0 means no modification.

        touchpad = {
          natural_scroll = "true";
        };
      };

      cursor = {
        no_hardware_cursors = 1;
      };

      device = {
        name = "epic-mouse-v1";
        sensitivity = "-0.5";
      };

      gestures = {
        workspace_swipe = "true";
      };

      misc = {
        force_default_wallpaper = 1;
        disable_hyprland_logo = "true";
      };

      bind = [
        "$mainMod, RETURN, exec, $terminal"
        "$mainMod SHIFT, Q, killactive"
        "$mainMod SHIFT, E, exit"
        "$mainMod SHIFT, SPACE, togglefloating"
        "$mainMod, C, exec, qalculate-gtk"
        "$mainMod, B, exec, zen"
        "$mainMod, D, exec, pkill $menu || $menu "
        "$mainMod, F, fullscreen"
        ", PRINT, exec, hyprshot -m region --clipboard-only"
        "$mainMod, PRINT, exec, hyprshot -m window"
        "$mainMod SHIFT, PRINT, exec, hyprshot -m output"
        "$mainMod, Tab, exec, pypr expose"
        "$mainMod, PERIOD, exec, pkill bemenu-openconfig || bemenu-openconfig"

        "$mainMod, F1, exec, pypr zoom +4"
        "$mainMod SHIFT, F1, exec, pypr zoom"

        "$mainMod, h, movefocus, l"
        "$mainMod, l, movefocus, r"
        "$mainMod, k, movefocus, u"
        "$mainMod, j, movefocus, d"

        "$mainMod SHIFT, h, movewindow, l"
        "$mainMod SHIFT, l, movewindow, r"
        "$mainMod SHIFT, k, movewindow, u"
        "$mainMod SHIFT, j, movewindow, d"

        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, 6, workspace, 6"
        "$mainMod, 7, workspace, 7"
        "$mainMod, 8, workspace, 8"
        "$mainMod, 9, workspace, 9"

        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod SHIFT, 6, movetoworkspace, 6"
        "$mainMod SHIFT, 7, movetoworkspace, 7"
        "$mainMod SHIFT, 8, movetoworkspace, 8"
        "$mainMod SHIFT, 9, movetoworkspace, 9"
        "$mainMod SHIFT, 0, movetoworkspace, 10"

        "$mainMod, S, togglespecialworkspace, magic"
        "$mainMod SHIFT, S, movetoworkspace, special:magic"
        "$mainMod, SPACE, exec, pkill waybar || waybar"
        #"$mainMod, R, submap, resize"
        #", escape, submap, reset"
      ];

      #binde = [
      #", l, resizeactive, 50 0"
      #", h, resizeactive, -50 0"
      #", k, resizeactive, 0 -40"
      #", j, resizeactive, 0 40"
      #];
      bindel = [
        ",XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"
        ",XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
        ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
        ",XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
        ",XF86MonBrightnessUp, exec, brightnessctl s 5%+"
        ",XF86MonBrightnessDown, exec, brightnessctl s 5%-"
      ];

      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:272, resizewindow"
      ];

      submap = [
        "resize"
        "reset"
      ];

      windowrulev2 = [
        #"opacity 0.9 0.7, class:^(zen)$"
        "opacity 0.9 0.7, class:^(nemo)$"
        "opacity 0.9 0.7, class:^(libreoffice-writer)$"
        "opacity 0.9 0.7, class:^(vesktop)$"
        "opacity 0.9 0.7, title:^Hyprland System Info$"
        "float, class:^(qalculate-gtk)"
        "float, class:^(nemo)"
      ];

      workspace = [
        "special:exposed,gapsout:60,gapsin:30,bordersize:5,border:true,shadow:false"
      ];

      "exec-once" = [ 
        "pypr"
        "waybar"
        "swww-daemon"
        #"eww daemon"
        "swww img ${config.home.homeDirectory}/Pictures/Wallpapers/wallpaper.png --transition-type grow --transition-pos 0.5,0.5 --transition-fps 60"
        #"eww open bar"
      ];

      "plugins:dynamic-cursors" = {
        enabled = "true";
        mode = "stretch";
        threshold = 2;

        # for mode = stretch
        stretch = {

          # controls how much the cursor is stretched
          # this value controls at which speed (px/s) the full stretch is reached
          limit = 12000;

          # relationship between speed and stretch amount, supports these values:
          # linear             - a linear function is used
          # quadratic          - a quadratic function is used
          # negative_quadratic - negative version of the quadratic one, feels more aggressive
          function = "negative_quadratic";
        };


        shake = {
          # enables shake to find
          enabled = "false";

          # use nearest-neighbour (pixelated) scaling when shaking
          # may look weird when effects are enabled
          nearest = "true";

          # controls how soon a shake is detected
          # lower values mean sooner
          threshold = 6.0;

          # magnification level immediately after shake start
          base = 4.0;
          # magnification increase per second when continuing to shake
          speed = 4.0;
          # how much the speed is influenced by the current shake intensitiy
          influence = 0.0;

          # maximal magnification the cursor can reach
          # values below 1 disable the limit (e.g. 0)
          limit = 0.0;

          # time in millseconds the cursor will stay magnified after a shake has ended
          timeout = 2000;

          # show cursor behaviour `tilt`, `rotate`, etc. while shaking
          effects = "true";

          # enable ipc events for shake
          # see the `ipc` section below
          ipc = "false";
        };

        hyprcursor = {

          # use nearest-neighbour (pixelated) scaling when magnifing beyond texture size
          # this will also have effect without hyprcursor support being enabled
          # 0 / false - never use pixelated scaling
          # 1 / true  - use pixelated when no highres image
          # 2         - always use pixleated scaling
          nearest = "0";

          # enable dedicated hyprcursor support
          enabled = "true";

          # resolution in pixels to load the magnified shapes at
          # be warned that loading a very high-resolution image will take a long time and might impact memory consumption
          # -1 means we use [normal cursor size] * [shake:base option]
          resolution = (-1);

          # shape to use when clientside cursors are being magnified
          # see the shape-name property of shape rules for possible names
          # specifying clientside will use the actual shape, but will be pixelated
          fallback = "clientside";
        };
      };

    };
  };
}
